services:
  - type: web
    name: ebuss-recommender
    env: python
    region: oregon
    branch: main

    # Pin Python here so Render doesn’t default to 3.13
    pythonVersion: 3.11.9

    buildCommand: |
      pip install -r requirements.txt
      python prepare_artifacts.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2

    autoDeploy: true