services:
  - type: web
    name: ebuss-recommender
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cp artifacts/*.pkl ."
    startCommand: "gunicorn app:app --preload --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: OPENBLAS_NUM_THREADS
        value: "1"
