services:
  - type: web
    name: ebuss-sentiment
    env: python
    branch: main
    # install deps, pull LFS files, and (optionally) rebuild your artifacts 
    buildCommand: |
      pip install -r requirements.txt
      git lfs pull           # <— add this if you keep pickles in LFS
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
