services:
  - type: web
    name: ebuss-sentiment
    env: python
    branch: main
    buildCommand: |
      echo "🛠 CUSTOM BUILD"
      pip install -r requirements.txt && python prepare_artifacts.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: IMPLICIT_NO_CUDA
        value: "1"

